base_images:
  ocp_builder_rhel-8-golang-1.22-openshift-4.18:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.22-openshift-4.18
  ocp_builder_rhel-9-base-openshift-4.18:
    name: builder
    namespace: ocp
    tag: rhel-9-base-openshift-4.18
  ocp_builder_rhel-9-golang-1.22-openshift-4.18:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.22-openshift-4.18
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.22
images:
- dockerfile_path: Dockerfile.openshift
  inputs:
    ocp_builder_rhel-8-golang-1.22-openshift-4.18:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.22-openshift-4.18
    ocp_builder_rhel-9-base-openshift-4.18:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-base-openshift-4.18
    ocp_builder_rhel-9-golang-1.22-openshift-4.18:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18
  to: multus-whereabouts-ipam-cni
- dockerfile_path: Dockerfile.test.openshift
  inputs:
    ocp_builder_rhel-9-golang-1.22-openshift-4.18:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18
  to: whereabouts-testing
promotion:
  to:
  - name: "4.19"
    namespace: ocp
releases:
  initial:
    integration:
      name: "4.19"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.19"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: whereabouts-unit
  commands: |
    cd /go/src/github.com/k8snetworkplumbingwg/whereabouts
    go mod tidy
    go mod vendor
    go mod verify
    make test-skip-static
  container:
    from: whereabouts-testing
- as: e2e-aws
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: security
  optional: true
  steps:
    env:
      ALL_PROJECTS: "true"
      PROJECT_NAME: whereabouts-cni
    workflow: openshift-ci-security
zz_generated_metadata:
  branch: main
  org: openshift
  repo: whereabouts-cni
